import React from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, Database, ShieldAlert, Github } from 'lucide-react';

const About: React.FC = () => {
  return (
    <div className="min-h-screen bg-white">
      <div className="bg-surface-secondary border-b border-ink-quaternary pt-10 pb-8 px-5">
        <div className="max-w-[760px] mx-auto">
          <p className="text-brand text-[12px] font-semibold uppercase tracking-[0.12em] mb-1">About</p>
          <h1 className="text-[28px] font-bold text-ink tracking-tight">What HealthInsureAI is, and isn't.</h1>
          <p className="text-ink-secondary text-[14px] mt-2 max-w-[560px]">
            A transparent look at how this workbench works, what data it uses, and where the AI stops.
          </p>
        </div>
      </div>

      <div className="max-w-[760px] mx-auto px-5 py-10 space-y-8">
        <section>
          <h2 className="text-[18px] font-bold text-ink mb-3">What this is</h2>
          <p className="text-ink-secondary text-[14px] leading-relaxed">
            HealthInsureAI is a data science workbench for exploring how machine learning and generative AI can
            support health insurance underwriting. It generates a synthetic portfolio of patient records, lets
            you benchmark classical ML and deep learning models against it, and uses the Gemini API to produce
            risk classifications, premium estimates, and narrative reports on demand.
          </p>
        </section>

        <section className="bg-surface-secondary rounded-2xl p-6 space-y-5">
          {[
            {
              icon: Database,
              title: 'The dataset is synthetic',
              desc: 'Every record — age, BMI, blood pressure, claims history, and more — is procedurally generated. No real patient data is used, stored, or transmitted anywhere.',
            },
            {
              icon: Sparkles,
              title: 'Predictions are AI estimates',
              desc: 'Risk categories, premium figures, feature importances, and report narratives are all generated by the Gemini API from the inputs you provide. They illustrate what an AI-assisted workflow could look like — they are not calibrated actuarial output.',
            },
            {
              icon: ShieldAlert,
              title: 'Not underwriting or medical advice',
              desc: 'Nothing in this tool should be used to make real coverage, pricing, or medical decisions. If you\'re looking for guidance on your own health or insurance, talk to a licensed professional.',
            },
          ].map(({ icon: Icon, title, desc }) => (
            <div key={title} className="flex gap-4">
              <div className="w-10 h-10 rounded-xl bg-white shadow-card flex items-center justify-center text-brand flex-shrink-0">
                <Icon size={18} />
              </div>
              <div>
                <h3 className="font-semibold text-ink text-[14px] mb-1">{title}</h3>
                <p className="text-ink-secondary text-[13px] leading-relaxed">{desc}</p>
              </div>
            </div>
          ))}
        </section>

        <section>
          <h2 className="text-[18px] font-bold text-ink mb-3">How it's built</h2>
          <p className="text-ink-secondary text-[14px] leading-relaxed mb-3">
            React, TypeScript, and Vite on the frontend; Recharts and Plotly for visualization; the Gemini API
            for every AI-generated feature. The whole app is a static client-side build, deployed on GitHub
            Pages via GitHub Actions.
          </p>
          <a
            href="https://github.com/yifeng22100/health-insurance-ai-application"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 text-brand text-[14px] font-semibold hover:underline"
          >
            <Github size={16} /> View the source on GitHub
          </a>
        </section>

        <section>
          <h2 className="text-[18px] font-bold text-ink mb-3">Related project</h2>
          <p className="text-ink-secondary text-[14px] leading-relaxed">
            If you're interested in navigating actual hospitals and healthcare providers rather than insurance
            modeling, check out{' '}
            <a
              href="https://yifeng22100.github.io/hospital-intelligence-my/#/"
              target="_blank"
              rel="noopener noreferrer"
              className="text-brand font-semibold hover:underline"
            >
              Healthcare Intelligence
            </a>
            , a companion project covering hospital discovery, cost references, and health knowledge for
            Malaysia.
          </p>
        </section>

        <section className="border-t border-ink-quaternary pt-6">
          <p className="text-ink-secondary text-[14px] leading-relaxed">
            Want to explore more first? Head to the{' '}
            <Link to="/dataset" className="text-brand font-semibold hover:underline">
              Dataset Explorer
            </Link>{' '}
            or browse{' '}
            <Link to="/health-tips" className="text-brand font-semibold hover:underline">
              Health Tips
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
};

export default About;
